if (typeof Materialize === "undefined") {
  Materialize = {};
}

Materialize.BACKGROUND_COLORS = [
  "red lighten-5",
  "red lighten-4",
  "red lighten-3",
  "red lighten-2",
  "red lighten-1",
  "red",
  "red darken-1",
  "red darken-2",
  "red darken-3",
  "red darken-4",
  "red accent-1",
  "red accent-2",
  "red accent-3",
  "red accent-4",
  "pink lighten-5",
  "pink lighten-4",
  "pink lighten-3",
  "pink lighten-2",
  "pink lighten-1",
  "pink",
  "pink darken-1",
  "pink darken-2",
  "pink darken-3",
  "pink darken-4",
  "pink accent-1",
  "pink accent-2",
  "pink accent-3",
  "pink accent-4",
  "purple lighten-5",
  "purple lighten-4",
  "purple lighten-3",
  "purple lighten-2",
  "purple lighten-1",
  "purple",
  "purple darken-1",
  "purple darken-2",
  "purple darken-3",
  "purple darken-4",
  "purple accent-1",
  "purple accent-2",
  "purple accent-3",
  "purple accent-4",
  "deep-purple lighten-5",
  "deep-purple lighten-4",
  "deep-purple lighten-3",
  "deep-purple lighten-2",
  "deep-purple lighten-1",
  "deep-purple",
  "deep-purple darken-1",
  "deep-purple darken-2",
  "deep-purple darken-3",
  "deep-purple darken-4",
  "deep-purple accent-1",
  "deep-purple accent-2",
  "deep-purple accent-3",
  "deep-purple accent-4",
  "indigo lighten-5",
  "indigo lighten-4",
  "indigo lighten-3",
  "indigo lighten-2",
  "indigo lighten-1",
  "indigo",
  "indigo darken-1",
  "indigo darken-2",
  "indigo darken-3",
  "indigo darken-4",
  "indigo accent-1",
  "indigo accent-2",
  "indigo accent-3",
  "indigo accent-4",
  "blue lighten-5",
  "blue lighten-4",
  "blue lighten-3",
  "blue lighten-2",
  "blue lighten-1",
  "blue",
  "blue darken-1",
  "blue darken-2",
  "blue darken-3",
  "blue darken-4",
  "blue accent-1",
  "blue accent-2",
  "blue accent-3",
  "blue accent-4",
  "light-blue lighten-5",
  "light-blue lighten-4",
  "light-blue lighten-3",
  "light-blue lighten-2",
  "light-blue lighten-1",
  "light-blue",
  "light-blue darken-1",
  "light-blue darken-2",
  "light-blue darken-3",
  "light-blue darken-4",
  "light-blue accent-1",
  "light-blue accent-2",
  "light-blue accent-3",
  "light-blue accent-4",
  "cyan lighten-5",
  "cyan lighten-4",
  "cyan lighten-3",
  "cyan lighten-2",
  "cyan lighten-1",
  "cyan",
  "cyan darken-1",
  "cyan darken-2",
  "cyan darken-3",
  "cyan darken-4",
  "cyan accent-1",
  "cyan accent-2",
  "cyan accent-3",
  "cyan accent-4",
  "teal lighten-5",
  "teal lighten-4",
  "teal lighten-3",
  "teal lighten-2",
  "teal lighten-1",
  "teal",
  "teal darken-1",
  "teal darken-2",
  "teal darken-3",
  "teal darken-4",
  "teal accent-1",
  "teal accent-2",
  "teal accent-3",
  "teal accent-4",
  "green lighten-5",
  "green lighten-4",
  "green lighten-3",
  "green lighten-2",
  "green lighten-1",
  "green",
  "green darken-1",
  "green darken-2",
  "green darken-3",
  "green darken-4",
  "green accent-1",
  "green accent-2",
  "green accent-3",
  "green accent-4",
  "light-green lighten-5",
  "light-green lighten-4",
  "light-green lighten-3",
  "light-green lighten-2",
  "light-green lighten-1",
  "light-green",
  "light-green darken-1",
  "light-green darken-2",
  "light-green darken-3",
  "light-green darken-4",
  "light-green accent-1",
  "light-green accent-2",
  "light-green accent-3",
  "light-green accent-4",
  "lime lighten-5",
  "lime lighten-4",
  "lime lighten-3",
  "lime lighten-2",
  "lime lighten-1",
  "lime",
  "lime darken-1",
  "lime darken-2",
  "lime darken-3",
  "lime darken-4",
  "lime accent-1",
  "lime accent-2",
  "lime accent-3",
  "lime accent-4",
  "yellow lighten-5",
  "yellow lighten-4",
  "yellow lighten-3",
  "yellow lighten-2",
  "yellow lighten-1",
  "yellow",
  "yellow darken-1",
  "yellow darken-2",
  "yellow darken-3",
  "yellow darken-4",
  "yellow accent-1",
  "yellow accent-2",
  "yellow accent-3",
  "yellow accent-4",
  "amber lighten-5",
  "amber lighten-4",
  "amber lighten-3",
  "amber lighten-2",
  "amber lighten-1",
  "amber",
  "amber darken-1",
  "amber darken-2",
  "amber darken-3",
  "amber darken-4",
  "amber accent-1",
  "amber accent-2",
  "amber accent-3",
  "amber accent-4",
  "orange lighten-5",
  "orange lighten-4",
  "orange lighten-3",
  "orange lighten-2",
  "orange lighten-1",
  "orange",
  "orange darken-1",
  "orange darken-2",
  "orange darken-3",
  "orange darken-4",
  "orange accent-1",
  "orange accent-2",
  "orange accent-3",
  "orange accent-4",
  "deep-orange lighten-5",
  "deep-orange lighten-4",
  "deep-orange lighten-3",
  "deep-orange lighten-2",
  "deep-orange lighten-1",
  "deep-orange",
  "deep-orange darken-1",
  "deep-orange darken-2",
  "deep-orange darken-3",
  "deep-orange darken-4",
  "deep-orange accent-1",
  "deep-orange accent-2",
  "deep-orange accent-3",
  "deep-orange accent-4",
  "brown lighten-5",
  "brown lighten-4",
  "brown lighten-3",
  "brown lighten-2",
  "brown lighten-1",
  "brown",
  "brown darken-1",
  "brown darken-2",
  "brown darken-3",
  "brown darken-4",
  "grey lighten-5",
  "grey lighten-4",
  "grey lighten-3",
  "grey lighten-2",
  "grey lighten-1",
  "grey",
  "grey darken-1",
  "grey darken-2",
  "grey darken-3",
  "grey darken-4",
  "blue-grey lighten-5",
  "blue-grey lighten-4",
  "blue-grey lighten-3",
  "blue-grey lighten-2",
  "blue-grey lighten-1",
  "blue-grey",
  "blue-grey darken-1",
  "blue-grey darken-2",
  "blue-grey darken-3",
  "blue-grey darken-4",
  "black",
  "white"
];

Materialize.TEXT_COLORS = _.map(Materialize.BACKGROUND_COLORS, function(color) {
  if (color.indexOf(" ") !== -1) {
    return color.replace(" ", "-text text-");
  } else {
    return color + "-text";
  }
});

Materialize.ICONS = [
  "3d_rotation",
  "accessibility",
  "account_balance",
  "account_balance_wallet",
  "account_box",
  "account_circle",
  "add_alert",
  "add_shopping_cart",
  "airplay",
  "alarm",
  "alarm_add",
  "alarm_off",
  "alarm_on",
  "album",
  "android",
  "announcement",
  "aspect_ratio",
  "assessment",
  "assignment",
  "assignment_ind",
  "assignment_late",
  "assignment_return",
  "assignment_returned",
  "assignment_turned_in",
  "autorenew",
  "av_timer",
  "backup",
  "book",
  "bookmark",
  "bookmark_border",
  "bug_report",
  "build",
  "business",
  "cached",
  "call",
  "call_end",
  "call_made",
  "call_merge",
  "camera_enhance",
  "card_giftcard",
  "card_membership",
  "card_travel",
  "change_history",
  "check_circle",
  "chrome_reader_mode",
  "class",
  "closed_caption",
  "code",
  "credit_card",
  "dashboard",
  "delete",
  "description",
  "dns",
  "done",
  "done_all",
  "eject",
  "equalizer",
  "error",
  "error_outline",
  "event",
  "event_seat",
  "exit_to_app",
  "explicit",
  "explore",
  "extension",
  "face",
  "fast_forward",
  "fast_rewind",
  "favorite",
  "favorite_border",
  "feedback",
  "find_in_page",
  "find_replace",
  "flight_land",
  "flight_takeoff",
  "flip_to_back",
  "flip_to_front",
  "forward_5",
  "forward_10",
  "forward_30",
  "games",
  "get_app",
  "gif",
  "grade",
  "group_work",
  "hd",
  "hearing",
  "help",
  "help_outline",
  "highlight_off",
  "high_quality",
  "history",
  "home",
  "hourglass_empty",
  "hourglass_full",
  "http",
  "https",
  "info",
  "info_outline",
  "input",
  "invert_colors",
  "label",
  "label_outline",
  "language",
  "launch",
  "library_add",
  "library_books",
  "library_music",
  "list",
  "local_hospital",
  "local_hotel",
  "local_laundry_service",
  "local_library",
  "local_mall",
  "local_movies",
  "local_offer",
  "local_parking",
  "local_pharmacy",
  "lock",
  "lock_open",
  "lock_outline",
  "loop",
  "loyalty",
  "markunread_mailbox",
  "mic",
  "mic_none",
  "mic_off",
  "movie",
  "new_releases",
  "note_add",
  "not_interested",
  "offline_pin",
  "open_in_browser",
  "open_in_new",
  "open_with",
  "pageview",
  "pause",
  "pause_circle_filled",
  "pause_circle_outline",
  "payment",
  "perm_camera_mic",
  "perm_contact_calendar",
  "perm_data_setting",
  "perm_device_information",
  "perm_identity",
  "perm_media",
  "perm_phone_msg",
  "perm_scan_wifi",
  "picture_in_picture",
  "playlist_add",
  "play_arrow",
  "play_circle_filled",
  "play_circle_outline",
  "play_for_work",
  "polymer",
  "power_settings_new",
  "print",
  "query_builder",
  "question_answer",
  "queue",
  "queue_music",
  "radio",
  "receipt",
  "recent_actors",
  "redeem",
  "reorder",
  "repeat",
  "repeat_one",
  "replay",
  "replay_5",
  "replay_10",
  "replay_30",
  "report_problem",
  "restore",
  "room",
  "schedule",
  "search",
  "settings",
  "settings_applications",
  "settings_backup_restore",
  "settings_bluetooth",
  "settings_brightness",
  "settings_cell",
  "settings_ethernet",
  "settings_input_antenna",
  "settings_input_component",
  "settings_input_composite",
  "settings_input_hdmi",
  "settings_input_svideo",
  "settings_overscan",
  "settings_phone",
  "settings_power",
  "settings_remote",
  "settings_voice",
  "shop",
  "shopping_basket",
  "shopping_cart",
  "shop_two",
  "shuffle",
  "skip_next",
  "skip_previous",
  "snooze",
  "sort_by_alpha",
  "speaker_notes",
  "spellcheck",
  "stars",
  "star_rate",
  "stop",
  "store",
  "subject",
  "subtitles",
  "supervisor_account",
  "surround_sound",
  "swap_horiz",
  "swap_vert",
  "swap_vertical_circle",
  "system_update_alt",
  "tab",
  "tab_unselected",
  "theaters",
  "thumbs_up_down",
  "thumb_down",
  "thumb_up",
  "toc",
  "today",
  "toll",
  "track_changes",
  "translate",
  "trending_down",
  "trending_flat",
  "trending_up",
  "turned_in",
  "turned_in_not",
  "verified_user",
  "videocam",
  "videocam_off",
  "video_library",
  "view_agenda",
  "view_array",
  "view_carousel",
  "view_column",
  "view_day",
  "view_headline",
  "view_list",
  "view_module",
  "view_quilt",
  "view_stream",
  "view_week",
  "visibility",
  "visibility_off",
  "volume_down",
  "volume_mute",
  "volume_mute",
  "volume_off",
  "volume_off",
  "volume_up",
  "volume_up",
  "warning",
  "web",
  "web",
  "work",
  "youtube_searched_for",
  "zoom_in",
  "zoom_out"
];
